# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2013
  project: Varnish Cache Control
  version: 1.0
  release: 1.0.1
  latex_documents:
  - - Index
    - vcc.tex
    - Varnish Cache Control
    - Nicole Cordes
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
